"shuffleFetchItems":false
"shuffleNPCItems":true
"shuffleTreasures":true
"shuffledShops":true
"preserveFiendRefights":false
"shortTemple":false
"chaosRush":false
"transformFinalFormation":false
"extraShards":false
"shardHunt":false
"itemMagic":false
"magicPermissions":false
"magicLevels":true
"magicShops":false
"allowUnsafePirates":false
"enemyStatusAttacks":true
"enemySkillsSpells":true
"enemyScripts":true
"confusedOldMen":true
"titansTrove":true
"skyCastle4F":false
"ordealsPillars":true
"extendedOpenProgression":true
"allowDeepCastles":false
"mapOpenProgression":true
"incentiveFetchItems":false
"incentiveTail":true
"incentiveFetchNPCs":false
"incentiveFreeNPCs":true
"incentiveSeaShrine":false
"incentiveOrdeals":true
"incentiveIceCave":false
"incentiveVolcano":false
"incentiveEarth":false
"incentiveMarsh":false
"incentiveSkyPalace":false
"incentiveMarshLocked":false
"incentiveConeria":true
"incentiveBad":false
"incentive65k":false
"incentiveRibbon2":false
"incentiveRibbon":false
"incentiveOpalBracelet":false
"incentiveMasamune":false
"incentiveOtherCastWeapon":false
"incentiveOffCastWeapon":false
"incentiveDefCastWeapon":false
"incentiveOtherCastArmor":false
"incentiveOffCastArmor":false
"incentiveDefCastArmor":false
"onlyRequireGameIsBeatable":false
"crownlessOrdeals":true
"earlySage":true
"earlySarda":true
"freeOrbs":false
"freeAirship":false
"freeBridge":true
"weaponStats":true
"enemyScaleFactor":1.8
"priceScaleFactor":4
"expMultiplier":2.4
"expBonus":0
"encounterRate":30
"forcedParty":0
"dungeonEncounterRate":30
"bossScaleFactor":1.8

/**************************************/
/*   These have varying degrees of    */
/* breaking shit in entertaining ways */
/**************************************/
"floorShuffle":false
"townShuffle":false
"entranceShuffle":false

/**************************************/
/*  These shouldn't affect anything.  */
/**************************************/
"waitWhenUnrunnable":true
"randomLoot":false
"randomWares":false 
"fisherPriceTurnOrder":true
"enemyElementalResistBug":true
"enemySpellsTargetingAllies":true
"enemyStatusAttackBug":true
"wrapPriceOverflow":false
"wrapStatOverflow":false
"houseMPRestore":true
"startingGold":false
"identifyTreasures":true
"buyTen":true
"dash":true
"noPartyShuffle":true
"speedHacks":true
"blackBeltAbsorb":true
"spellBugs":true
"chanceToRun":true 
"easyMode":false
"enableCritDisplay":true 
"randomTrapFormations":false
"enemyTrapTiles":true
"enemyFormationsSurprise":true
"enemyFormationsUnrunnable":true
"enemyFormationsFrequency":true
"rng":true
"waitWhenUnrunnable":true
